### ISSUE TITLE
Remove repo.remove (or fix it, if it's still useful)

### ISSUE THREAD

**Issue by Pomax** [michael/github#108]
when I call the .remove() function, I keep getting these errors:

```
POST https://api.github.com/repos/Pomax/gh-blog/git/trees?1393981519258 422 (Unprocessable Entity) api.github.com/repos/Pomax/gh-blog/git/trees?1393981519258:1
POST https://api.github.com/repos/Pomax/gh-blog/git/commits?1393981519451 422 (Unprocessable Entity) api.github.com/repos/Pomax/gh-blog/git/commits?1393981519451:1
Uncaught TypeError: Cannot read property 'sha' of undefined 
```

The network responses for the failed URLs are

```
{
  "message": "Must supply tree.sha or tree.content",
  "documentation_url": "http://developer.github.com/v3/git/trees/#create-a-tree"
}
```

and

```
{
  "message": "Validation Failed",
  "documentation_url": "http://developer.github.com/v3/git/commits/#create-a-commit",
  "errors": [
    {
      "value": null,
      "resource": "Commit",
      "field": "tree",
      "code": "missing"
    }
  ]
}
```

respectively.

**Comment by IFPRMENA** [comment]
Remove() or Delete() doesn't work for me. They actually behave the same and give me the same error "Uncaught SyntaxError: Unexpected number" in the browser when calling this method. Any update on this? Would really appreciated.

**Comment by aendrew** [comment]
Huh. I just opened #175, given I ran into repo.remove and repo.delete while improving test coverage. Do we need both of these? Or will one working "remove a file or blob from a repo" function suffice? If so, which should it be called, and should the other be preserved in some capacity for backwards compatibility?

**Comment by aendrew** [comment]
This thing generates so many issues and I want it fixed yesterday. Giving it P1 for next release.

**Comment by aendrew** [comment]
This is fixed by c895f.

**Comment by aendrew** [comment]
For future reference, I ended up removing repo.delete (did the exact same thing as repo.remove but was an uglier implementation) and aliased it to repo.remove.
