### ISSUE TITLE
Fix all the UMD loading stuff — for realsies this time!

### ISSUE THREAD

**Issue by w35l3y** [michael/github#117]
Is there any chance of changing all references of "window" to "this" in github.js ?

I *think* it shouldn't affect the current behavior.
I am trying to use this script with Greasemonkey but it doesn't work the way it currently is.

**Comment by aendrew** [comment]
There've always been some issues with how the UMD stuff is currently set up. Changing title to better reflect underlying issue.

**Comment by aendrew** [comment]
I've completely redone the UMD boilerplate, see #1431e27.

PLEASE —

1. Report whether the aforementioned commit works with how you use Github.js.
2. Report whether you're instantiating Github.js via Node.js, AMD (Require.js et al) or browser globals
3. Report any problems you may have.

Many thanks everyone! We'll kill this bug yet!
