### ISSUE TITLE
Having trouble getting repo.fork() to work.

### ISSUE THREAD

**Issue by adelevie** [michael/github#124]
This could be me, but I documented my issue [here](http://stackoverflow.com/questions/25609238/forking-a-repo-with-the-github-api-with-client-side-javascript-and-oauth-io).

Generally, speaking, what scopes are needed in the API application to fork a public repo (from an organization)? Mine are set to `repo` and `public_repo` but I get a 404 from running:

```javascript
var repo = github.getRepo("michael", "github");
  
// this works
repo.show(function(err, myRepo) { console.log(myRepo); });
  
// this does not
repo.fork(function(err) {
  console.log(err);
});
```

**Comment by aendrew** [comment]
This is over a year old now. Closing as unable to confirm.

**Comment by alejost848** [comment]
I'm having the same problem, I'm trying to fork a user repo but I can't get it working.

```javascript
//I create the Github instance
var github = new Github({
  username: "user",
  password: "pass",
  auth: "basic"
});

//Then get the repo
var repo = github.getRepo("alejost848", "polytipe");

//I print it on the console to see if it is working (it is)
repo.show(function(err, repo) {
  console.log(repo);
});

//I try to fork the repo, but it's not working
repo.fork(function(err) {});

//Creating a new repo works though
var user = github.getUser();
user.createRepo({"name": "test"}, function(err, res) {});
```

What am I missing here? Thanks.
