### ISSUE TITLE
Improve test suite

### ISSUE THREAD

**Issue by aendrew** [michael/github#149]
I really like this library, and I read your bit in the README about it being used in production by Prose.io users (and thus not needing a test suite), but I kind of disagree. You should *definitely* have a full test suite for this, especially if you're wanting to encourage pull requests. With a test suite, regressive issues like #147 probably wouldn't have happened.

I'm happy to contribute tests if that helps!

**Comment by aendrew** [comment]
Well, three months later — this definitely needs to happen. I'm giving four weeks for the current spate of PRs to add unit tests to their commits and then replacing the tape-based infrastructure with a proper Gulp-driven Karma-based test suite, or at least automate running the unit tests by adding it to some sort of tooling.

**Comment by aendrew** [comment]
As per #174 — here are where unit tests are needed. Cookies and beer to whoever helps:

+ `User.repos`
+ `Repo.deleteRepo` // This might be a false positive.
+ `Repo.updateTree`
+ `Repo.getRef`
+ `Repo.createRef`
+ `Repo.deleteRef`
+ `Repo.createRepo` // Might be another false positive.
+ `Repo.listTags`
+ `Repo.listPulls`
+ `Repo.getPull`
+ `Repo.compare`
+ `Repo.getBlob`
+ `Repo.getTree`
+ `Repo.postBlob`
+ `Repo.updateTree`
+ `Repo.postTree`
+ `Repo.updateHead`
+ `Repo.branch`
+ `Repo.createPullRequest`
+ `Repo.listHooks`
+ `Repo.getHook`
+ `Repo.createHook`
+ `Repo.editHook`
+ `Repo.deleteHook`
+ `Repo.remove`
+ `Repo.delete`
+ `Repo.move`
+ `Repo.getCommits`
+ `Gist constructor`
+ `Gist.read`
+ `Gist.create`
+ `Gist.delete`
+ `Gist.fork`
+ `Gist.update`
+ `Gist.star`
+ `Gist.unstar`
+ `Gist.isStarred`
+ `Issue constructor`
+ `GitHub.getIssues`
+ `GitHub.getGist`

I wouldn't double a number of these aren't documented in README.md either — extra marks to anyone who adds them!

**Comment by aendrew** [comment]
Sundry testing todos:
1. ln. 76 — Add basic test for token auth.
2. ln. 47 — Add test for URL paths.
3. ln. 94 — Add erroring test for _requestAllPages
4. ln. 103, 109-110 — Add test for paginated request (pref. >1000 items)
5. ln. 241 — Does updateTree still do anything?

**Comment by aendrew** [comment]
Anyone wishing to collaborate on this, I'm working on aendrew/github#improving_tests — please PR to there for the moment. Thanks!

**Comment by aendrew** [comment]
Update: Coverage is now being logged in [CodeCov](https://codecov.io/github/michael/github/github.js?ref=6d84e30409c6a8b4e09a262eb947ef8c43b4cf5c). Wanna write some tests? Check there!

**Comment by AurelioDeRosa** [comment]
Since we're using CodeCov, I feel this issue can be closed. We still need to improve coverage and some tests but the coverage is pretty good now.
