### ISSUE TITLE
Support OAuth for GitHub

### ISSUE THREAD

**Issue by iamale** [michael/github#165]
Since logging in using password is just uncool. Also, two-factor auth isn't supported when logging in with HTTP auth.

Possible things to do:

* [Personal access tokens](https://help.github.com/articles/creating-an-access-token-for-command-line-use)
* Real OAuth flow, e. g. via [hello.js](http://adodson.com/hello.js/) (a bit harder, but friendlier)

**Comment by gmaclennan** [comment]
You can already use personal access tokens as described in the [README](https://github.com/michael/github#usage).  Personal access tokens [will work for two-factor](https://developer.github.com/changes/2013-09-03-two-factor-authentication/).

**Comment by iamale** [comment]
Oh, sorry! Wrong repo. I'm so disorganized. This issue was meant for some other project using this library, I just mixed two tabs up.
