### ISSUE TITLE
Github oauth changes

### ISSUE THREAD

**Issue by IFPRMENA** [michael/github#170]
My application stop working because of this authorization API change that gihub recent update. Is there an update to this? 
This is not working for me now: 
var github = new Github({
  token: "OAUTH_TOKEN",
  auth: "oauth"
});

Please, let me know. Thank you

**Comment by gajjargaurav** [comment]
I tried it today and it's working absolutely fine. please try again (ensure that token value is present)

**Comment by aendrew** [comment]
I don't think this is valid; I tried using OAuth just yesterday and it worked fine.

Please do the following:
1. Generate a new OAuth token on GitHub and try using that.
2. If that fails, please post an example JSFiddle of what you're doing so I can troubleshoot it better.

Thanks! Will reopen if there's a continued issue.
