### ISSUE TITLE
Parallel writes to the same repo

### ISSUE THREAD

**Issue by gmaclennan** [michael/github#171]
I don't know if anyone else has shared the problem of making multiple writes to the same repo and dealing with fast forward commits and conflict. You will likely get an error like `refs/heads/master expected to be at ee1cd720841a4b5b06a8339c333c56b1748e66f9`

Spent this weekend tackling this problem in [Hubfs.js](https://github.com/gmaclennan/hubfs.js) and thought that some of the code might be useful for anyone who comes across this problem. Might be overkill for this library, since it ended up being a little tricky to implement. Basically, if a write is already in progress, subsequent writes are batched together and committed in a single commit when the current write is finished.

**Comment by aendrew** [comment]
@gmaclennan Hi! Thanks for that, looks interesting. TBH, I'm fairly new at maintaining this and I'm not sure it can even do batch writes in its present state; repo.write just does `PUT /repos/:owner/:repo/contents/:path` and doesn't do anything with the [Git data API](https://developer.github.com/v3/git/). 

So, getting that to work would be the first thing. Definitely taking another look at your implementation afterwards, though. :+1:

**Comment by gmaclennan** [comment]
No, it can't. If you `repo.write` a second time on the same repo before the first write is finished it will give an error. I was using this library before, but put together hubfs.js to overcome some issues like that. `repo.write` in this library used to use the Git data API, before the pull request that broke many things changed it. The contents API simplifies things, and reduces the number of requests which is great for browser implementations, but it has some shortcomings like a 1Mb limit for reads, and a [small issue](http://stackoverflow.com/questions/19576601/github-api-issue-with-file-upload) with consecutive writes sometimes failing if they are too close together.

**Comment by aendrew** [comment]
Putting in the queue for 0.10.8, giving P3. Ensuring writing functionality is able to handle things like multiple writes is important.

**Comment by AurelioDeRosa** [comment]
As I mention in [this article](http://www.audero.it/blog/2015/10/17/upload-files-on-github-using-github-js/) and as reported by [this StackOverflow comment](http://stackoverflow.com/questions/19576601/github-api-issue-with-file-upload#comment29081581_19576601) this seems not possible due to an issue of the API.

**Comment by AurelioDeRosa** [comment]
This issue can be closed. The temporary solution is described [here](http://www.audero.it/blog/2015/10/17/upload-files-on-github-using-github-js/). Once we fix [this issue](https://github.com/michael/github/issues/229), writing in parallel won't be necessary anymore.
