### ISSUE TITLE
Replace "that" variables with .bind()

### ISSUE THREAD

**Issue by aendrew** [michael/github#176]
"that" is used a lot to pass context into child functions, but it's not immediately apparent what's going on with that. Probably better to use [Function.prototype.bind()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind).

**Comment by AurelioDeRosa** [comment]
If we do that we have to add a polyfill for PhantomJS 1 (that we use for testing) as it doesn't support bind.

**Comment by AurelioDeRosa** [comment]
@aendrew In 0.11.0 we'll switch to ES6 and Babel and if we use the arrow function this issue will be automatically fixed. Can I close the issue?

**Comment by aendrew** [comment]
Yep, absolutely. Closing! :smile:
