### ISSUE TITLE
btoa not found (when running from a browser)

### ISSUE THREAD

**Issue by jgbarah** [michael/github#178]
Tested with "Firefox 38.0" and "Chromium Version 38.0.2125.101 Built on jessie/sid, running on Debian jessie/sid (290379)". When trying to write to a new file, I get an error about btoa not found.

```javascript
var github = new Github({
	token: token,
	auth: "oauth"
});
var repo = github.getRepo(user, reponame);
repo.write('master', 'data', "Hola", "First", function(err) {});
```

The error happens in the repo.write line. If instead of that one I have the wollowing one:

```javascript
repo.show(showRepo);
```

It calls showRepo, which is a function that shows the info about the repo perfectly.

After a bit of debugging, it seems that the problem is that btoa is not available at the moment of calling "write", but is needed by it.

Changing all invoking occurences of "btoa" to "window.btoa" in github.js, (three occurrences in total) fixes this. But I'm not sure this is the best way of fixing it, since it will probably not run if not in a browser... In addition, I see the code

```javascript
  if (typeof exports !== 'undefined') {
      XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
      _ = require('underscore');
      var btoa = require('btoa'); //jshint ignore:line
  } else { 
      _ = window._; 
  }
```

which maybe is set up for exactly this scenario, but I'm not sure why it is not working.

**Comment by aendrew** [comment]
I added `var` in [this commit](https://github.com/michael/github/commit/4e7b00f6474c6b57f0098a146c6196321aa5c362#diff-94dc46cf0d324912ab3cf7bed36dbcbbR24), which is probably what broke it. Marking as bug, will fix soon.

**Comment by jgbarah** [comment]
Thanks. I can confirm that removing that "var", it works as well.

**Comment by rolodato** [comment]
I installed v0.10.6 from bower and it still contains the `var`, which causes this same problem. Removing the `var` makes it work just fine:

```sh
$ bower install github && grep "var btoa" bower_components/github/github.js
bower github#*                  cached git://github.com/michael/github.git#0.10.6
bower github#*                validate 0.10.6 against git://github.com/michael/github.git#*
bower github#~0.10.6           install github#0.10.6

github#0.10.6 bower_components/github
        var btoa = require('btoa'); //jshint ignore:line```

**Comment by aendrew** [comment]
@rolodato I need to push a new release really badly; for now just use the master branch, where the above is fixed. Thanks!

**Comment by j5vii** [comment]
My preferred way to deal with dependencies like this is to pass them from the container as parameters, e.g.

```
(function (btoa, atob) {
...
}).call(this, btoa, atob);
```

When using this style, they variables-as-parameters will be declared, use strict won't complain, and any existing value will be retained.  You can also remove the initialization from the variable declaration and it will work properly, e.g.

```
var btoa, atob;
```

Does not shadow the window scope the way that

```
var btoa = undefined, atob = undefined;
```

does ...

Since there hasn't been a release, I almost wrote a duplicate ticket for this! :)
