### ISSUE TITLE
contents() ref does not work

### ISSUE THREAD

**Issue by raine** [michael/github#182]
You can pass any `ref` and it will always look for in master.

This is evident in github's response that has ref in `url` field for example.

**Comment by aendrew** [comment]
Could somebody please confirm this? If so, I'll give this P2 and prioritise it for 0.10.7.

**Comment by arbesfeld** [comment]
Also having this issue.

**Comment by aendrew** [comment]
Ah, I knew I'd seen this issue before. It's actually fixed already; see #224. Install from `master` instead of the latest release.
