### ISSUE TITLE
user/issues doesn't work when using OAuth

### ISSUE THREAD

**Issue by rclai** [michael/github#184]
Hello,

Locally I've added an additional API call on `Github.User` called `.issues()` (when authenticated via access token in OAuth) which does this:

```js
// Authenticated via
/*
GH = new Github({
  token: validToken,
  auth: 'oauth'
});
*/
Github.User = function() {
  //...
  this.issues = function(cb) {
    _request("GET", '/user/issues', {
      filter: 'subscribed',
      state: 'all',
      sort: 'updated',
      direction: 'desc'
    }, function(err, res) {
      cb(err, res);
    }, true);
  };
  // ...
}
```

Based on the [GitHub API documentation here](https://developer.github.com/v3/issues/#list-issues), shouldn't this work?

This is the error I get back:

```
{
  "error": 404,
  "path": "/user/issues",
  "request": {
    "onabort": null,
    "onerror": null,
    "onload": null,
    "onloadend": null,
    "onloadstart": null,
    "onprogress": null,
    "ontimeout": null,
    "readyState": 4,
    "response": "{\n  \"message\": \"Not Found\",\n  \"documentation_url\": \"https://developer.github.com/v3\"\n}\n",
    "responseText": "{\n  \"message\": \"Not Found\",\n  \"documentation_url\": \"https://developer.github.com/v3\"\n}\n",
    "responseType": "",
    "responseURL": "https://api.github.com/user/issues?1432435698158",
    "responseXML": null,
    "status": 404,
    "statusText": "Not Found",
    "timeout": 0,
    "upload": {
      "onabort": null,
      "onerror": null,
      "onload": null,
      "onloadend": null,
      "onloadstart": null,
      "onprogress": null,
      "ontimeout": null
    },
    "withCredentials": false
  }
}
```

**Comment by aendrew** [comment]
I just tried adding your code to a new test in [aendrew/github#user_issues](https://github.com/aendrew/github/tree/user_issues) and it works perfectly fine when using basic auth, but I can't seem to return any of my issues when using Oauth, for some reason. Can't seem to reproduce the error you have, though. 

Will leave issue open pending further investigation. In the meantime, @rclai — would you consider expanding on your code a bit and writing a PR? user.issues seems like something this library should have... Thanks!

**Comment by rclai** [comment]
[The commit](https://github.com/aendrew/github/commit/5f5269b5b82847329e7ebe30425e348761316a40) was literally the same code I used to get the issues. But what error were you getting?

Could this be an issue in the endpoint? My Github application simply has "public information" permissions.

**Comment by rclai** [comment]
Also, I'm running this on `localhost`, I don't know if that might have anything to do with it?

**Comment by aendrew** [comment]
@rclai I'm not getting any errors; if I use OAuth, I just get back an empty array. It's not `localhost`, I was running the tests from there myself. 

If you fetch my branch and run the tests yourself locally (`cd test && node test.user.js`), does it work?

**Comment by rclai** [comment]
Let me try.

**Comment by rclai** [comment]
I also got an empty array of issues too in basic auth. However, when I switched to oauth with my user token, I got a 404 on it (among other errors with the other tests).

**Comment by rclai** [comment]
Hello, :smile: just wondering how this issue is going? Is there any more information you guys need?

**Comment by aendrew** [comment]
After a bit of investigation, it's working as intended for me — try changing it from `/user/issues` to just `/issues`. Try the following:

`curl -H "Authorization: token <YOURTOKENHERE>" https://api.github.com/user/issues`
`curl -H "Authorization: token <YOURTOKENHERE>" https://api.github.com/issues`

The former returns an empty array for me, the latter all the issues I'm currently subscribed to. TBH I have no idea what the difference between those two endpoints is.

See: https://developer.github.com/v3/issues/#list-issues

**Comment by aendrew** [comment]
Update: I emailed GitHub about that and they got back to me with the following:

>Hi Ændrew,

I believe the confusion here may be related to the parameters available on those endpoints:

https://developer.github.com/v3/issues/#parameters

Do you see what you expect if you use the following URL instead?

https://api.github.com/user/issues?filter=all

The default "filter" value is "assigned", and you may not be assigned to any issues in your repositories.
Let me know if that's still not clear.

**Comment by rclai** [comment]
For user/issues?

**Comment by aendrew** [comment]
Yep, try it yourself:

`curl -H "Authorization: token <YOURTOKENHERE>" https://api.github.com/user/issues\?filter\=all`

**Comment by rclai** [comment]
Okay, but what happened to the `subscribed` filter option? I have some subscribed issues.

**Comment by aendrew** [comment]
Hmm, okay, that's a valid point. Okay, will take another look.

In the meantime, could you extend the code you've added and submit it as a PR? I'd like to ultimately add the /user/issues API and doing so will make it easier for me to support. Thanks!

**Comment by rclai** [comment]
Okay will do so tonight.

**Comment by rclai** [comment]
Well, since the roll out of the new Github header, I've since dropped the project that I was working on that relied on this `/issues/` endpoint. Took them long enough.. Geez..
