### ISSUE TITLE
Improve documentation for unauthenticated requests

### ISSUE THREAD

**Issue by soops** [michael/github#187]
I was wondering if you can use the unauthenticated requests? Like getting a public gist without authenticating the user.

**Comment by aendrew** [comment]
I don't think it does at the moment, but it really should. PRs welcome!

**Comment by sargeant45** [comment]
I found a work around. If you initialize a Github instance like this:
```javascript
var noauthgithub = new Github({});
```
It will allow you to make some requests with the gists and stuff. You just don't define anything in the options. The variable still exists, it just doesn't have anything in it so no `variable does not exist`  errors are thrown. Therefore, you don't *really* need to change anything, but I'll keep it open just in case somebody wants it to be official.

**Comment by aendrew** [comment]
@sargeant45 Ah! Good to know! I wasn't sure given there isn't really any documentation around it and it's not evident in any of the unit tests. Updating issue to be more documentation-related. Thanks!
