### ISSUE TITLE
publish latest to npm?

### ISSUE THREAD

**Issue by jonschlinkert** [michael/github#188]
You can always publish as beta if you're concerned about the latest release not being ready...

**Comment by aendrew** [comment]
@jonschlinkert Would love to, but I don't have permissions on NPM yet.

@michael or @ingalls — mind adding me to npmjs.org for github-api when you get a chance? Many thanks!

**Comment by jonschlinkert** [comment]
understood! thanks for the hard work on this, I'm totally fine waiting :)

**Comment by michael** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/2931/7800673/41cef84e-0319-11e5-94d3-ac86a72d2e87.png)

**Comment by aendrew** [comment]
@michael Awesome! Many thanks!
@jonschlinkert 0.10.6 now published!

**Comment by jonschlinkert** [comment]
great! thanks!
