### ISSUE TITLE
422 error on delete/write

### ISSUE THREAD

**Issue by lucusp** [michael/github#190]
This is probably user error but I'm getting a 422 (cannot completely) error when trying to delete a file or write to existing file. I'm sure I'm using it wrong.

**Comment by aendrew** [comment]
@lucusp Hi, could you please provide a JSFiddle approximating your code or at least explain what you're doing a bit better? You've provided effectively zero information... :sweat_smile: Thanks!

**Comment by lucusp** [comment]
Ok I will as soon as I can :) sorry for the vague info.

**Comment by lucusp** [comment]
Ok, so my issue is this (using jQuery):

         $.ajax({
		
			url: githubjs
		
		}).success(function(data){
		
			var content = data;
 
                        repo.write('master', _path, content, 'my commit message', function(err) {
                            
                                $('#tmpdump').text(JSON.stringify(err));
        
                        });	
         })

Looks like it's successful on my page but in the console I get this:

`https://api.github.com/repos/lucusp/test/contents/dir/pop.html?1433031143713 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)`

Hopefully this is more clear? It only does this when writing to an _existing_ file in a directory.

**Comment by lucusp** [comment]
Gonna close this issue due to #78, #85, #108 all being similar more practical examples of my issue(s).

**Comment by aendrew** [comment]
@lucusp Cool, thanks! Will look into those issues next chance I get!
