### ISSUE TITLE
Return promise if no callback specified

### ISSUE THREAD

**Issue by reportbase** [michael/github#191]
Is there a way to download multiple files, using promises.

Instead of this:
repos.contents("master", /path/to/a.json, function(error, result){})
repos.contents("master", /path/to/b.json, function(error, result){})
repos.contents("master", /path/to/c.json, function(error, result){})

How about doing this instead:
    var a = make_promise("GET", "json", "/path/to/a.json");
    var b = make_promise("GET", "json", "/path/to/b.json");
    var c = make_promise("GET", "json", "/path/to/c.json");

    Promise.all([a,b,c])
    .then(function(response)
    {

    },
    function()
    {
    });

**Comment by aendrew** [comment]
Hi!

I think the API for this is way too complex to wrap it all in a single function, but I'm totally on board for making the library nicer to use with promises.

That said, you can totally already use promises by using Q or Promise's `denodeify` method:

```javascript
var getRepoContents = Promise.denodeify(repo.contents);
var resultA = getRepoContents('master', '/path/to/a.json');
var resultB = getRepoContents('master', '/path/to/b.json');
var resultC = getRepoContents('master', '/path/to/c.json');
Promise.all([resultA, resultB, resultC])
  .then(function(response){ console.dir(response); }, function(err){ console.dir(err); });
```

Haven't tested the above but should work.

That said, it'd be really cool if all library methods returned promises if no callback is specified. Updating issue to reflect this...

**Comment by reportbase** [comment]
Cool.   Give me a skeleton of what you want and I'll wipe something up for my first patch.

**Comment by aendrew** [comment]
Maybe something similar to this?

http://mono.software/posts/Creating-NodeJS-modules-with-both-promise-and-callback-API-support-using-Q/

Please submit as a PR with unit tests if interested in adding this — thanks!
