### ISSUE TITLE
httprequest onprogress patch

### ISSUE THREAD

**Issue by reportbase** [michael/github#192]
I added a callback to httprequest for the onprogress callback.   
Can I submit this for review?

function _request(method, path, data, cb, raw, sync, onprogress) 
{
		xhr.onprogress = function(evt)
		{
			if (onprogress)
				onprogress(evt.loaded,evt.total);
		}        
      }
}

**Comment by aendrew** [comment]
Interesting — could you please submit it as a PR and add unit tests? Thanks!
