### ISSUE TITLE
btoa is undefined depending on the call context

### ISSUE THREAD

**Issue by firehist** [michael/github#196]
I work w/ TypeScript and angular framework. When I call for exemple `repo.write(...)` from a service method, `atob` is null whereas `window.atob` works well.

**Comment by aendrew** [comment]
I'm not sure I understand what the issue is. atob isn't ever even defined or used in github.js... Why is this necessary? What does this have to do with btoa, as per the issue title?

Further, your PR breaks the tests.

Please explain the issue better and I'll reopen. Thanks!

**Comment by firehist** [comment]
I'll do it ASAP.
I'll describe more this bug and fix tests!

**Comment by firehist** [comment]
Hello @aendrew 

It's the same problem on this issue #178 
Please find a jsfiddle to demonstrate the problem: http://jsfiddle.net/firehist/1a31jLzy/

Solutions are:
- remove the `var` to avoid hoisting
- declare `atob = window.atob`

Block browser usage.
Bennnou.

**Comment by aendrew** [comment]
@firehist It's not at all the same problem as #178 — that refers to *btoa* (base64 to ascii), not *atob* (ascii to base64). AFAIK, `github.js` makes no use of the latter, which is what you're proposing.

**Comment by firehist** [comment]
@aendrew My bad, I speak about #198 which fix `atob` and not `btoa`.

**Comment by aendrew** [comment]
@firehist That's your own pull request, which is still causing tests to fail...
