### ISSUE TITLE
Add starring for repositories

### ISSUE THREAD

**Issue by ssergienko** [michael/github#205]
hi, mate.
thanks for you job. use your plugin on a project and have fun ) 
I've added peace of code for starring of repositories here - https://github.com/ssergienko/github/commit/76f6b51a175c49376dee7e7f5980cd326e2badb4
don't know why so many changes are displaying, I've just added few lines.
the peace of code is:

// starring
            this.isStarred = function(owner, repo, cb) {
                _request("GET", "/user/starred/" + owner + '/' + repo, null, function(err,res) {
                    cb(err,res);
                });
            };
            this.star = function(owner, repo, cb) {
                _request("PUT", "/user/starred/" + owner + '/' + repo, null, function(err,res) {
                    cb(err,res);
                });
            };
            this.unstar = function(owner, repo, cb) {
                _request("DELETE", "/user/starred/" + owner + '/' + repo, null, function(err,res) {
                    cb(err,res);
                });
            };

hope it'll help

PS: fixed bug with "var btoa". now it works

thanks,
Serge

**Comment by aendrew** [comment]
Hi @ssergienko!

Mind submitting this as a pull request and adding tests? Also, I think you might have changed the indentation because it seems like 95% of the file is rewritten from your commit; please fix that before PR'ing.

Thanks!

**Comment by ssergienko** [comment]
ok, I'll try. I'm just very beginner on github, unlike development )

**Comment by aendrew** [comment]
@ssergienko No worries! We all start somewhere! Learning to do PRs is a really terrific skill to learn, really helps you become a bonafide member of the open source community. :smile:

**Comment by AurelioDeRosa** [comment]
Closing this issue as the methods have been introduced with commits 63b62ca0c6b02fd1ba62d0f33740641a9dd3531a, 1fd209d55efad56ad1812642a39a4e3a2ff50813, and 15b69aa54f8ee628d7d08f0fe94854cbd9351fad.
