### ISSUE TITLE
What does "developed in the context of Prose" mean exactly?

### ISSUE THREAD

**Issue by timbur** [michael/github#208]
I noticed that Prose hasn't been using this package for quite some time, so I'm curious as to what exactly that quote means.  Does it mean that whenever some GitHub API functionality is added to Prose, that same functionality is implemented here as well?

**Comment by aendrew** [comment]
@timbur That... Is a very good question. I think Prose.io helped develop it for awhile, but then aren't now, and I should really update the README? 

Hey, current co-maintainers — are DevelopmentSeed doing anything with this project anymore?

**Comment by timbur** [comment]
I guess we can take that as a no.  ;D
