### ISSUE TITLE
Publish new version to NPM

### ISSUE THREAD

**Issue by danielo515** [michael/github#224]
Hello,

First of all, thank you for such a great plugin. I have very good plans for it :smile: 
One thing that took my attention is that there is a commit that says: removed underscore dependency.  But, on the node.js version, on line 19 I can see how you require underscore. Is this intended or a mistake?

Regards

**Comment by aendrew** [comment]
Wat. Really?

Investigating...

**Comment by danielo515** [comment]
Hello @aendrew 
> By "node.js" version, do you mean the version on NPM? 

Yes, exactly. Sorry for not being clear enough.

>Please use the master branch for now, thanks!

That is what I was doing, and it is what I'm going to do. I just wanted to experiment the easiness of using npm

Regards

**Comment by aendrew** [comment]
New version released! Can finally close this!
