### ISSUE TITLE
Callback 'cb' Required

### ISSUE THREAD

**Issue by j5vii** [michael/github#227]
Current line 67 https://github.com/michael/github/blob/master/github.js#L67 requires `cb` (callback) to be defined.

It's not totally clear from examples whether the callback is needed, and the error doesn't give you the info you need to correct the issue if the callback is required.

**Comment by aendrew** [comment]
Bumping to 0.10.8, we really need to release 0.10.7.

**Comment by AurelioDeRosa** [comment]
Unfortunately the link doesn't refer to a specific version in time of the repository. So, after all the changes we've done it doesn't point to the intended line of code anymore. I'm closing this issue for now but feel free to update the reference and open it again.
