### ISSUE TITLE
Token security

### ISSUE THREAD

**Issue by imlestat** [michael/github#228]
Hi I don't know if this is the place to posting this but I'm a newby and I'm experimenting with this repo to interact directly with files on the browser. I'm using gatekeeper which sends back the oauth token and I'm using it directly on a script like this to later interact with my repo files:

$.getJSON('http://lestat.herokuapp.com/authenticate/'+code, function(data) {
	var github = new Github({
	  token: data,
	  auth: "oauth"
	});
});

I've read that tokens shouldn't be used on client side for security and the previous code declares the token client side but I've tried to access it through the browser console and it's not displayed so I think it's not accessible but I'm not sure. It's this approach secure?

**Comment by lucusp** [comment]
This blog post seems to make it sound ok:
https://github.com/blog/1509-personal-api-tokens

**Comment by aendrew** [comment]
Okay, so there's a difference between personal API tokens and OAuth user tokens:

You use personal API tokens to test things locally without having to do the 2-legged OAuth "request token, authorise application, send token to callback" workflow. You should never store these in your source code as they can be read by anyone using your app, and they ultimately give whoever's using them access to your account (limited only by the scope you set when you generate the personal token).

Oauth client tokens, meawhile, are essentially the same thing but generated as the result of the two-legged Oauth workflow described above. There are a few security considerations with these:

1. If you store the resultant token in localStorage or a cookie, it can then be read by malicious scripts and then used by an attacker.
2. If being sent across unencrypted HTTP, they're subject to the same sort of man-in-the-middle attacks that any form data would be. You shouldn't pass OAuth tokens around in insecure request.

Obligatory "I'm not a security researcher" caveat; it's possible I'm missing something.

Closing for the moment, but feel free to keep commenting on this and I'll respond if you need anything else. Thanks!

**Comment by lucusp** [comment]
@aendrew thanks for your feedback! My understanding, from the blog post, is that the Personal API Tokens are safe to send via https request. Is this incorrect? I'm working on an app that utilizes the personal access tokens for the reasons you stated but it's all processed client side. Maybe this is bad.

**Comment by aendrew** [comment]
@lucusp Is the only person using the app you? Again, if a user is interacting with GitHub via github.js using a personal access token, it's interacting with GitHub *as* whoever generated the personal access token.

**Comment by lucusp** [comment]
@aendrew yes, the user creates _their own token_ not mine.

**Comment by aendrew** [comment]
@lucusp But they're not creating a "personal access token" via GitHub, they're using OAuth, right? If so, then yes, as long as you're transmitting tokens over SSL, you'd probably* okay.

*"probably" because, again, I'm not a security researcher.

**Comment by lucusp** [comment]
@aendrew :( i have them going to GitHub and creating a token that way. Sounds like that's not a good thing. I really appreciate your help.

**Comment by lucusp** [comment]
Well, I found a project that can help with client side Oauth (for anyone interested): https://github.com/oauth-io/oauth-js

**Comment by aendrew** [comment]
@lucusp Ah! I see what you're doing now. I guess that works fine, but it's a bit unnecessary and probably somewhat inconvenient for your users (Also prone to error if they need a specific scope). Oauth.io is fantastic, have used it previously!

**Comment by lucusp** [comment]
@aendrew ok cool. Thanks for responding. I was getting a little worried. Still going to implement Oauth.io, but that means the project is "safe" for the time being. Keep up the good work!
