### ISSUE TITLE
Request: Adding more mantainers

### ISSUE THREAD

**Issue by AurelioDeRosa** [michael/github#230]
Hi there.

This project is quite popular and it's a bit of a shame that it isn't updated regularly. There are many issues open and several PRs ready to be merged that would improve this library even more. In addition, there are several very useful but undocumented methods like `getCommits()` and `listTags()`.

I'm opening this issue/proposal to ask the owner to add more maintainers to the project so that the development of this project can move forward.

**Comment by olivierbeaulieu** [comment]
+1

**Comment by michael** [comment]
Who is interested in becoming one of the maintainers? I'm open to adding more, however @aendrew should decide on that.

**Comment by AurelioDeRosa** [comment]
I'm keen to help with you with the project if you want.

**Comment by aendrew** [comment]
Hey everyone, apologies for the huge delay in getting back to the library, have been massively snowed under at work. 

There are a bunch of changes in `master` and a new release needs to be rolled; plus we're back up to nearly 40 open PRs. We really need a coordinated effort on this project beyond merely my occasional dropping in to close issues and merge PRs. Ultimately I'd like to have a team of at least four people managing the issue queue and generally maintaining the library.

That said, I feel the codebase needs to get a bit more under control before adding that many more maintainers to the mix — part of what broke everything the last time 'round was maintainers haphazardly merging commits without testing. While the test coverage is much, much better than it was, it's still only about 70% IIRC.

For now:

+ @michael, please add @AurelioDeRosa to the list of maintainers. Thanks!
+ @AurelioDeRosa, thanks for offering to help. Please start by working on the PR backlog, starting from oldest, using the following rules:
    + If a PR doesn't include unit tests, please request them. 
    + Also please ensure all code is properly linted. 
    + Have PR submitters squash commits before merging.
    + If a PR is against a version of the code more than four releases from current, you can probably just close it (especially if it won't merge cleanly). If it seems like a particularly valuable PR, feel free to request the contributor update it, though I leave that at your discretion. 
    + If the source repo has been deleted (i.e., there's no way the submitter can modify their PR), you can probably just close it. Again, leaving it to your discretion — if it's a valuable PR nobody else has bothered with and it's clean code that has unit tests, you might be able to still merge it. But at this point, don't fret if you have to close stuff without merging.
    + As per @michael's initial suggestions as per when I took over, this library looks to be a light implementation of the GitHub API; it doesn't necessarily need to cover everything. Prioritise stability improvements and things like Node interoperability over new features.
    + If you want to do code improvements, maybe start with improving test coverage. I'm using Istanbul at the moment, though am totally into migrating to [CodeCov](https://codecov.io).
    + For your first few merges, if you want me to double-check them, please just tag as "RTBC" and mention me in a comment. I'll then double-check them as quickly as possible and merge the change.

Once we get nearer to 100% code coverage and have the things I've mentioned above canonised into a CONTRIBUTORS.md document (i.e., we have solid community standards and straight-forward ways for both contributors to submit code and maintainers to approve code), I'll open things up to adding a few more contributors and we can develop this a bit more collaboratively.

**Comment by AurelioDeRosa** [comment]
Hi @aendrew.

Thank you very much for the information. I'll follow your directions and take the other decisions on a per-case basis. I look forward to give my contribution to this project. I'll wait for you to add me as a mantainer.

**Comment by michael** [comment]
Done. Thanks guys!

**Comment by aendrew** [comment]
:+1: Thanks, @michael!
