### ISSUE TITLE
Add Gitter integration

### ISSUE THREAD

**Issue by aendrew** [michael/github#236]
@michael, please add a webhook to `https://webhooks.gitter.im/e/08ecead3d96383ac83ea` — this will allow integration with the [Gitter channel](https://gitter.im/michael/github) I've created. Thanks!

**Comment by michael** [comment]
I've added a Gitter service hook, but not sure i used the right API token. 

![image](https://cloud.githubusercontent.com/assets/2931/10575325/e02df8cc-765b-11e5-8c39-898ab3647c5c.png)

Can you check if things are working?

**Comment by aendrew** [comment]
@michael Seems to be working! Thanks! 
![screen shot 2015-10-19 at 11 38 52](https://cloud.githubusercontent.com/assets/185041/10575673/064bd002-7656-11e5-975b-2d2e3d867b18.png)
