### ISSUE TITLE
Replace Tape with Karma + (Mocha, Jasmine or Qunit)

### ISSUE THREAD

**Issue by aendrew** [michael/github#237]
Testling has apparently been borked for a year. It should be removed, especially because we're using Travis for CI anyway. See substack/testling#88.

**Comment by aendrew** [comment]
We probably still should have some browser-side testing. To that end, I propose we replace Testling with Sauce Labs and am reopening this as a result.

**Comment by michael** [comment]
We had good experiences with just using PhantomJS for browser-side testing.

See: https://github.com/substance/substance/blob/master/test/unit/ui/component.test.js

Since there is no click testing etc. involved maybe Selenium is a bit of an overkill for Github.js.

**Comment by aendrew** [comment]
@michael Fair point! Know if there's any way to run Tape tests in the browser without doing something like using Browserify and something like [tape-run](https://github.com/juliangruber/tape-run)?

**Comment by michael** [comment]
Don't know anything about tape, but for our qUnit scenario we use some gulp script to 'build' a test bundle before running it.

https://github.com/substance/substance/blob/master/gulpfile.js#L54-L69

**Comment by aendrew** [comment]
@michael Interesting. TBTH I'm honestly thinking tape-run is the best option, as it involves no rewriting of unit tests and means they'll run both in Node and in browser (plus it has support for all the main browsers). Only downside of using that in place of Testling or PhantomJS is that there isn't the snazzy testing matrix for the README.

**Comment by michael** [comment]
That's perfectly fine I would say. The cross browser matrix thing is useful if you test UI interactions in a range of browsers.

**Comment by AurelioDeRosa** [comment]
Wow, I've just realized that on Gitter I commented about this. I think we could move to a more mainstream testing library like Mocha or QUnit. Since this is a library meant to work in browsers, ideally Karma or BrowserStack should be used as well.

**Comment by aendrew** [comment]
Mocha + Karma sounds good to me. The only real reason to keep Tape would be Testling integration, which doesn't even work anymore (that all said, I kind of like Tape tests, they're super easy to understand). 

Converting the existing specs is probably a 2-3 hour job for when somebody gets bored... Any takers?

**Comment by AurelioDeRosa** [comment]
I can take this task. My thinking right now is that we could take all this big features we're planning to do (new tests, promises, maybe splitting the lib into modules) and create a new branch (0.11.0).

**Comment by michael** [comment]
I had some not so nice experiences with mocha, related to debuggability in the browser. I couldn't easily find the position where the error happened and set a breakpoint. qUnit with the try-catch option enabled did the job well for us. But please if you go for a new test suite, just reevaluate the available options. Probably mocha has also evolved since then.

**Comment by aendrew** [comment]
FWIW, using `tape-run` does not work at all, and won't help test things like XHR in #14 and #45.

If we want want to test both in the browser and CLI we need to use something like Mocha + Karma.

**Comment by aendrew** [comment]
Fixed by 1813b0d0965d460158fbeec4f2ad3d7a9becd9ba.
