### ISSUE TITLE
Rewrite inline comments to make use of jsDoc

### ISSUE THREAD

**Issue by aendrew** [michael/github#239]
jsDoc is terrific and well-supported, makes reading the code itself easier and allows the creation of full API docs with trivial effort. We should endeavour to rewrite all inline comments using jsDoc.

**Comment by michael** [comment]
:+1: we also recently starting generating docs for Substance using jsDoc. 

E.g. http://substance.io/docs/module-ui_surface.ContainerEditor.html

We also made a little script that reacts to a web hook to trigger regeneration of docs on every commit to master.

However, for Substance there's a long way to go until we have each module covered.  Github.js as a single-file could be documented quite fast.

Thanks to @aendrew et al. for turning Github.js into a professional test-covered project! You really do a great job!

**Comment by AurelioDeRosa** [comment]
100% agree on jsDoc.

**Comment by clayreimann** [comment]
To Do:
* [ ] Evaluate themes
  * [ ] [Documentation Jekyll](http://idratherbewriting.com/documentation-theme-jekyll/)
  * [ ] [minami](https://github.com/nijikokun/minami)
* [ ] Auto publish to [gh-pages](https://www.npmjs.com/package/gh-pages)

**Comment by clayreimann** [comment]
Closed by e0666fd, opening new for auto-publishing
