### ISSUE TITLE
Create official website for documentation and promotion

### ISSUE THREAD

**Issue by aendrew** [michael/github#242]
It would be really cool to have a proper non-GitHub promotional and documentation site like most large open source projects — am thinking githubjs.org. No idea when this would happen, but probably after 0.11.0 is in flight.

**Comment by lucusp** [comment]
I think I could help with this! I've been wanting to get involved but my skills on adding to the library are far from up to snuff. I *think* I could make a site for the lib that I use and love! Could we just use gh-pages for the hosting and add a CNAME/Domain to that? That's usually what I do.

**Comment by lucusp** [comment]
Also, if you have some sites you'd like to model it after post them here and I'll take a look and start a mock.

**Comment by aendrew** [comment]
Hi @lucusp! Thanks for volunteering, that's terrific!

I think an examples and reference section would be helpful (Perhaps similar to [c3js.org](http://www.c3js.org) works, and I also really like how [Angular](http://angularjs.org) includes unit tests in its examples as a way of both how to write the tests and as a declarative way of explaining the library.  I also like [Moment.js](http://momentjs.com/)' design, will add more as I think of them. :smile:

**Comment by lucusp** [comment]
Awesome! I'll give it a go and put my best foot forward! At the very least we'll have something up for someone to help it along ;)

**Comment by AurelioDeRosa** [comment]
I'd vote for GitHub pages as well so everyone can contribute easily.

**Comment by aendrew** [comment]
Yep, +1 for gh-pages.

**Comment by AurelioDeRosa** [comment]
@lucusp any update on this?

**Comment by lucusp** [comment]
@AurelioDeRosa sadly I do not. Another time consuming project has come up. I would like to still help with it but I don't think I should take the lead.

**Comment by AurelioDeRosa** [comment]
Hi @lucusp. Are you still interested in helping us?

**Comment by EliCDavis** [comment]
@AurelioDeRosa What all features would you like the site to have?

**Comment by AurelioDeRosa** [comment]
I think it should contain all the info included in the README and the HTML output of JSdoc documentation that we'll write.

**Comment by EliCDavis** [comment]
I've set up [websites](http://videogamedev.club/) before (never a gh-page), but I'm just a student.  I'd be willing to help though If no one takes this over.

**Comment by AurelioDeRosa** [comment]
In this case maybe you can start with easier and smaller tasks. Have a look at the other issues labelled as [PRs welcome](https://github.com/michael/github/labels/PRs%20welcome). Thank you for the interest.

**Comment by clayreimann** [comment]
Website is now available. https://michael.github.io/github/

**Comment by AurelioDeRosa** [comment]
That's awesome @clayreimann. Thank you very much for your recent work. I'm hoping to help again very soon.

On a side note, is Yahoo sponsoring GitHub.js now? I'm asking because I saw the footer of the website.

**Comment by clayreimann** [comment]
Sponsoring, not really–just allowing me to work on it.
