### ISSUE TITLE
Decide upon community code standards

### ISSUE THREAD

**Issue by aendrew** [michael/github#243]
As we move towards rewriting the lib in modern ECMAScript, we should probably decide upon some standards beyond what's specified with jsHint. JSHint itself is moving towards being more of a code sanity checker and less of a code formatter, which is why JSCS has popped up. I'm also a fan of clang-format, which is nearly zero-config and works brilliantly.

To that end, we should probably decide the following things:
* JSCS or clang-format?
* Spaces vs. tabs
* 4 vs. 2 indentation
* double or single quotes?
* other stuff?

My personal preference is for clang-format + tabs + 2 indentation + single quotes. Please comment if you prefer something otherwise. N.b., I reserve the right to lock this thread at any time if it gets too bikeshed-y.

**Comment by AurelioDeRosa** [comment]
Here are my thoughts:

- I'd go with JSCS as it has an awesome community. It also has [a tool for jsDoc](https://github.com/jscs-dev/jscs-jsdoc) and integration with Grunt
- Spaces
- [3 spaces](http://www.audero.it/blog/2015/10/21/the-revolution-of-3-spaces-code-indentation/)
- Single quotes

**Comment by aendrew** [comment]
What if we used JSCS for jsDoc linting and clang-format for auto-formatting projects? I'm almost even on board with the 3-spaces idea, though I worry that less experienced contributors will screw it up. *However*, if we use something that's able to reliably format code to standards, anyone can use anything they want and clangformat will correct it to whatever we decide upon as a standard.

**Comment by AurelioDeRosa** [comment]
In regard of your point about how many spaces, I think we'll definitely fix everything using a tool. I don't mind using something other than JSCS. Does is it have the some amount of options? I'm asking because I don't have experience with it. Just a FYI, JSCS has a fix option as well.

**Comment by AurelioDeRosa** [comment]
What we should use for tooling? Grunt, Gulp, or simply npm?

**Comment by aendrew** [comment]
I'm aware JSCS has a fix option, but have no idea how accurate or effective it is. Granted, I don't have a ton of experience with clangformat either; autoformatting the code on commit is slightly new territory for me. See [this](http://clangformat.com/) for .clangformat options.

re: tooling — for the 0.10.x series, if we're going to use Karma, it's probably worthwhile setting up some sort of task runner. Happy to set up some Gulp tasks, wouldn't take long at all. Gasp, we could even have a minified version that way! :sweat_smile: 

For 0.11.x, Gulp and Babel work really well together. I'm not opposed to the idea of just using NPM to do everything as it reduces dependencies, but I find I can write much more complex tasks that look much nicer in `package.json` if there's a build tool involved.

**Comment by AurelioDeRosa** [comment]
Cool! Let's use Gulp then. I'm very keen to see how it works compared to Grunt.

**Comment by aendrew** [comment]
I've looked a bit more into clang-format, and it doesn't seem to support enforcing a type of quotation marks. Given as such (and because the mixing of single and double quotes in the test suite is driving me crazy), let's use JSCS.

**Comment by AurelioDeRosa** [comment]
Cool. Let's use JSCS. Should we use preset format to save time or do we want to create our own?

**Comment by aendrew** [comment]
@AurelioDeRosa I'm pretty impartial. Feel free to just grab somebody else's.

**Comment by AurelioDeRosa** [comment]
This issue is closed by https://github.com/michael/github/commit/c3d5bb6fdd7cb330d808b69b80278d890e0c34bc.

**Comment by aendrew** [comment]
Cool! :+1:
