### ISSUE TITLE
The library should specify browsers supported

### ISSUE THREAD

**Issue by AurelioDeRosa** [michael/github#245]
At the moment there is no clear indication of which browsers the library supports.

**Comment by aendrew** [comment]
Maybe we should use Sauce Labs after all? Probably better for multi-browser testing than just Travis.

**Comment by AurelioDeRosa** [comment]
Fine with that

**Comment by aendrew** [comment]
This is resolved via d2fc035e10eb0d16b6320d37e11f486e4927006a.
