### ISSUE TITLE
Support pagination in the repos API

### ISSUE THREAD

**Issue by icco** [michael/github#25]
github ignores per_page values larger than 100. So your get repos call only returns the first 100 repos.

http://developer.github.com/v3/#pagination

**Comment by revolunet** [comment]
same for issues

**Comment by aendrew** [comment]
This is fixed for the the Issues API in merged PR #100, should work if you clone Master (Should probably bump the version sometime soon). I swear I saw a PR somewhere yesterday that does the same to the Repos API, though feel free to have a dig and submit a PR if that isn't in fact the case. Thanks!

**Comment by aendrew** [comment]
I'm going to make sure this works in 0.10.7.

**Comment by AurelioDeRosa** [comment]
What's the action on this issue? I can't see where we should replace the `_request` call with `__requestAllPages` for the Repository API

**Comment by aendrew** [comment]
Bumping to 0.10.8, we really need to release 0.10.7.

**Comment by adjohnson916** [comment]
+1 Is this supposed to work yet? 0.10.7 was released.
