### ISSUE TITLE
Custom b64encode to be moved for Browser + Browserify?

### ISSUE THREAD

**Issue by AurelioDeRosa** [michael/github#251]
In PR #203 we added a custom `b64encode()` function. Should we use it with the browser when we use Browserify? Does it have any consequence on executing `atob()` before passing the string to a method like `repo.write()` for example when writing images and other files?

**Comment by aendrew** [comment]
This is kind of like the last issue I that needs to be dealt with before releasing 0.10.7. I think we're probably okay — the tests are working both in Karma and Mocha, though an additional test for writing images and whathaveyou wouldn't hurt.

**Comment by aendrew** [comment]
Okay, so here's where `b64encode` is used:

+ [`Basic` authentication][basic] (Tested in [test.auth][basic-test])
+ [`repo.postBlob`][postBlob] (No unit test)
+ [`repo.write`](https://github.com/michael/github/blob/master/github.js#L800) (Tested in test.repo [here][write-test1] and [here][write-test2]

[basic]: https://github.com/michael/github/blob/master/github.js#L98
[basic-test]: https://github.com/michael/github/blob/master/test/test.auth.js#L20
[postBlob]: https://github.com/michael/github/blob/master/github.js#L539
[write-test1]: https://github.com/michael/github/blob/master/test/test.repo.js#L148
[write-test2]: https://github.com/michael/github/blob/master/test/test.repo.js#L159

**Comment by aendrew** [comment]
Just wrote a test uploading an image using repo.write — totally breaks it. :-1:
