### ISSUE TITLE
Why karma-phantomjs-launcher is in the "dependencies" ?

### ISSUE THREAD

**Issue by phodal** [michael/github#258]
Currently, I work on a side project with Atom Electron, and I use this libs to access GitHub API. 

But when I package the application, I found the size added more than 40M. Finally, and I found the  ``karma-phantomjs-launcher`` is the reason, I think it should be in "devDependencies".

**Comment by aendrew** [comment]
Yikes, really? When'd that happen? Will push a fix to that momentarily, thanks for letting us know!

**Comment by phodal** [comment]
@aendrew Thanks for your quick fix.

When use the Electron to package the application, it will also package the  node_modules. In the prev verison, the libs ``karma``, ``phantomjs`` was depended by ``karma-phantomjs-launcher``, those packages will also be package to application. the size of ``karma`` almost 30M, and  ``phantomjs`` will be 15M.

**Comment by aendrew** [comment]
@phodal Yep, is definitely a problem. Would also be problematic for Browserify and Webpack users.
