### ISSUE TITLE
node-XMLHttpRequest doesn't work in AMD (and breaks Webpack, and possibly Browserify)

### ISSUE THREAD

**Issue by aendrew** [michael/github#259]
Currently AMD tries to load node-xmlhttprequest as a dependency, and given that library doesn't have a UMD, everything breaks. This is particularly problematic with Webpack, because it tries to load the AMD version and fails upon first XHR use.

Will be resolved via #252.

Thanks to @patrykkopycinski for the report!

**Comment by pizn** [comment]
I have encountered this problem. What time released v0.10.8?

**Comment by ldd** [comment]
I made a really ugly fix to use this with webpack: https://gist.github.com/ldd/c1a20595765fab416ebe

I hope v0.10.8 fixes everything :)

**Comment by AurelioDeRosa** [comment]
This will be fixed in version 0.10.8. A preview can be seen [here](https://github.com/michael/github/pull/280).

**Comment by AurelioDeRosa** [comment]
Issue fixed and it'll be available when we release the new version.
