### ISSUE TITLE
Methods name consistency

### ISSUE THREAD

**Issue by AurelioDeRosa** [michael/github#262]
We have mixed names for our methods. Some of them starts with a verb (`getPull`) and others don't (`gists`). Moreover, when using a verb to retrieve information it's not consistent. Sometimes we use "get" (`getPull`) and other times we use "list" (`listPulls`). We should stick with one convention and follow it.

Since this would be a breaking change, the target version should be 0.11.0.

**Comment by clayreimann** [comment]
Closed by e0666fd
