### ISSUE TITLE
Meteor JS package is now available

### ISSUE THREAD

**Issue by nirpeled** [michael/github#270]
I recently started to play with Meteor JS and was looking for a good GitHub API wrapper for it, unfortunately I couldn't find one but then found out about this awesome library and decided to wrap a package of it for all Meteor JS users like me - check it out at https://github.com/nirpeled/meteor-github

Install: ``` meteor add nirpeled:meteor-github ```

@michael keep up the good work and happy new year!! :)

Nir

**Comment by aendrew** [comment]
That's awesome! Thanks @nirpeled!

**Comment by aendrew** [comment]
Adding documentation label, stuff like this should be mentioned in README somewhere.

**Comment by AurelioDeRosa** [comment]
Hi @nirpeled. I'm not a Meteor user so I'd like to understand more about your package. In which way it wraps Github.js? What it does to the library that allows it to be used in Meteor? In other words isn't possible to use Github.js as it is in Meteor?

**Comment by AurelioDeRosa** [comment]
Hi @nirpeled. Did you have the chance to look at my questions?

**Comment by nirpeled** [comment]
Hi @AurelioDeRosa,
I'm so sorry for my late response.
Meteor has its own package manager similar to npm for NodeJS. Therefore, I thought it was nicer to wrap Github.js as a package - it's easier to upgrade that way and plus, with Meteor, once you install it as a package, it will be available globally for both client and server environments which is kinda cool.
Nir

**Comment by AurelioDeRosa** [comment]
I've heard that Meteor is moving to npm. With this in mind, is this package still necessary?

**Comment by nirpeled** [comment]
No, once Meteor switches to npm - this package won't be necessary anymore.

**Comment by clayreimann** [comment]
Closing since Meteor is switching to npm
