### ISSUE TITLE
Bad URL for UMD Boilerplate Code in github.js

### ISSUE THREAD

**Issue by ckehoe** [michael/github#276]
The URL for the UMD Boilderplate Code in github.js is incorrect. The URL should be: https://github.com/umdjs/umd/blob/master/templates/returnExportsGlobal.js

**Comment by AurelioDeRosa** [comment]
Hi @ckehoe.

Thank you for opening this issue. I've actually deleted that comment since it doesn't add any real value. If we keep it we might need to update it in the future if the repository changes home, which seems an unnecessary effort.
