### ISSUE TITLE
pull request merge

### ISSUE THREAD

**Issue by benjamine** [michael/github#278]
is there a method to merge a pull request?
(if not, would you be interested on adding it?)

https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

**Comment by AurelioDeRosa** [comment]
Hi @benjamine.

We don't have such method but we're interested in adding it. Would you mind submit a PR?

**Comment by benjamine** [comment]
cool, yes, I'll give it a try

**Comment by AurelioDeRosa** [comment]
FYI,  in case you want this plus some other method , you can take a look at [this project of mine called GitHub Extended](https://github.com/github-tools/github-extended#methods)

**Comment by benjamine** [comment]
oh interesting, already sent the PR to add it here, but I'll take a look.
