### ISSUE TITLE
Newbie question... how can I avoid "TypeError: Base64 is undefined"

### ISSUE THREAD

**Issue by dalareo** [michael/github#285]
I am learning to use the library, in order to get data from Github and build a dynamic website but...

what am I doing wrong?? This is my html sandbox file:

    <!doctype html>
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="">
    </head>
    <body>
    <script src="github.js" type="text/javascript"></script>
    <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <script type="text/javascript">
    var github = new Github({
    username: 'dalareo',
    password: '**********',
    reponame: 'wemooc',
    auth: 'basic'
    });
    var user = github.getUser();
    user.orgs(function(err, orgs) {});
    </script>
    </body>
   </html>

**Comment by AurelioDeRosa** [comment]
Hi.

If you don't want to use a module loader such as Browserify or RequireJS, you need to use the file called `github.bundle.min.js` inside the `dist` folder. By the way, I'm closing this issue as it isn't a bug with the library.

**Comment by dalareo** [comment]
Thanks @AurelioDeRosa

**Comment by enki-code** [comment]
@AurelioDeRosa Including that information in the Read Me would be extremely helpful.. Having to search through closed issues to find out why my implementation wasn't working is troublesome.

I too didn't use a module loader, but wanted to test this out in jsFiddle, and kept getting axios is not defined.

Would you mind adding something about this to the Installation section?
