### ISSUE TITLE
Include documentation on the creation of hooks in the ReadMe

### ISSUE THREAD

**Issue by Jack-Collins** [michael/github#295]
Sorry if this is the wrong place -  I have been trying to set up a Travis hook via the github api using this library but can not find any documentation on this in the readme, or anywhere else. If somebody knows how to do it, it would be a great addition to this repo's readme I think.

**Comment by AurelioDeRosa** [comment]
You can start [here](https://developer.github.com/webhooks/) but for sure this is something we should document.

**Comment by clayreimann** [comment]
Should add https://tonicdev.com/clayreimann/5722a004b9583b1100c8adf3 to the documentation

**Comment by Jack-Collins** [comment]
```javascript
var options = {
	        "name" : "travis",
		"config" : {
					"user" : "your-Username",
					"token" : "00000000000000000000000000",
					"domain" : "http://notify.travis-ci.org",
					"content_type": "json"
					},
		"events" : ["push", "pull_request"],
		"active" : true
		}
		//create the git-travis hook
		try{
            fork.createHook(options, function(){
			    console.log("A travis hook has been created which will trigger a build on push and pull request events...");
		    });
        }
		catch(err){
             console.log(err);
        }
```

**Comment by Jack-Collins** [comment]
I successfully created a travis hook using the above. Wasn't sure where to document it...

**Comment by clayreimann** [comment]
@Jack-Collins the best place to document it would be to add an example in the `gh-pages` branch.

**Comment by Jack-Collins** [comment]
pr here: https://github.com/michael/github/pull/336
