### ISSUE TITLE
Automatic dist generation

### ISSUE THREAD

**Issue by clayreimann** [michael/github#299]
We should automate our release workflow (especially as we add more targets, e.g. bower, typescript, etc.).

This will probably mean that we no longer need to host the `dist/` files directly on github. We could use [cndjs](https://github.com/cdnjs/cdnjs) instead of github as our CDN if just depending on NPM/Bower is insufficient.

To Do:
* [ ] evaluate [this recipe](https://github.com/gulpjs/gulp/blob/master/docs/recipes/automate-release-workflow.md)
* [ ] PR to cdnjs

**Comment by AurelioDeRosa** [comment]
Considering the amount of people that are confused about the file to use, I'm fine with that.

**Comment by clayreimann** [comment]
Closed by e0666fd, opening new issue for cdnjs PR
