### ISSUE TITLE
Creating issue is not working

### ISSUE THREAD

**Issue by samprity** [michael/github#301]
I tried using the issue api. 

_var github = new Github();
			var options = {
			title: "Found a bug",
			body: "I'm having a problem with this.",
			assignee: "samprity",
			  milestone: 1,
			  labels: [
				"Label1",
				"Label2"
			  ]
			};	
	var issues = github.getIssues("samprity", "JSLint1");
issues.create(options, function(err, issue) {});_

But I am getting this error : 
![image](https://cloud.githubusercontent.com/assets/15081743/13630387/00ed4e58-e594-11e5-9cea-6061316fd1b0.png)

**Comment by AurelioDeRosa** [comment]
Hi.

The screenshot doesn't really help us since it doesn't show the error. What's the exact error are you receiving? How did you use the library?

**Comment by samprity** [comment]
its says that axios is not a function. I have used the library in index.html : 
<script type = "text/javascript" src = "github.js"></script>

**Comment by AurelioDeRosa** [comment]
I'm pretty sure your issue is related to the fact that you included the wrong file as specified https://github.com/michael/github/issues/285#issuecomment-180782156. In regard of your question, website hosted on github.io have an underlying repo, so the answer is yes.
