### ISSUE TITLE
Cannot read property 'apiUrl' of undefined

### ISSUE THREAD

**Issue by dolbyzerr** [michael/github#303]
I am trying to create Github instance without authentication

```javascript
const github = new Github()
```
and having this error
```
Cannot read property 'apiUrl' of undefined
```

I looked through the code and found out that it was fixed (https://github.com/michael/github/blob/master/src/github.js#L46)

Please publish this fix to npm :)

**Comment by AurelioDeRosa** [comment]
Closing this issue as it has already been solved.

**Comment by saa-lem** [comment]
How was the issue solved because I have the same error
