### ISSUE TITLE
can't get issues.list options to work 

### ISSUE THREAD

**Issue by MarceloEmmerich** [michael/github#305]
this returns the same regardless of what I put in the options object:

```JavaScript
var options = {
    state:'closed',
    since : '2015-04-00T00:00:00Z'
};
issues.list(options, function(err, issues) {});
```
Any idea what I am doing wrong?

**Comment by AurelioDeRosa** [comment]
@clayreimann Can you have a look at this issue?

**Comment by clayreimann** [comment]
@MarceloEmmerich Can you provide more information on where you're seeing this issue? Web vs node, if browser which and what version? What user/repo are you querying?

**Comment by clayreimann** [comment]
Closed by e0666fd

**Comment by clayreimann** [comment]
@MarceloEmmerich `v1.0.0` is out, are you still affected?

**Comment by MarceloEmmerich** [comment]
sorry for delay in response, moved away to another solution as I needed results... will try v1.0.0 now and let you know how it goes

**Comment by clayreimann** [comment]
No problem, it took a while to fix the issue. If you're not using the library then don't worry about it (unless you're going to come back).
