### ISSUE TITLE
listBranches() only returns the last component of the branch path

### ISSUE THREAD

**Issue by timrchavez** [michael/github#31]
After looking at the code, it looks like this was done intentionally, but I'm not sure why.  I feel I should be able to pass the values returned by listBranches() to getRef() (appended to "heads/") without issue, but if I have a branch 'feature/foo', listBranches() will return 'foo', and getRef() will fail.

**Comment by olivierbeaulieu** [comment]
Fixed [here](https://github.com/michael/github/pull/231)

**Comment by aendrew** [comment]
Fixed by #231. Thanks, @olivierbeaulieu!
