### ISSUE TITLE
issues.get is not a function

### ISSUE THREAD

**Issue by msdark** [michael/github#311]
I'm seeing this error when trying to get one issue

    issues.get(issueNumber, function (err, issue) {
	       ^
    TypeError: issues.get is not a function
      at getIssue (hearForGithubIssues.js:12:9)
      at Object.<anonymous> (hearForGithubIssues.js:67:10)

Code:

    const github = new Github({
	token: token,
        auth: 'oauth'
    })
    const issues = github.getIssues(userName, repoName)
    issues.get(issueNumber, (err, issue) => {
       if(err){
           error(err)
            return
       }
       callback(issue)
    })

**Comment by clayreimann** [comment]
Not sure what's causing this, investigating.

**Comment by msdark** [comment]
I'm using ES6 to write the code so i'm importing the code like this
`import github from ' github-api'`

**Comment by msdark** [comment]
I found the issue.. https://github.com/michael/github/blob/v0.11.2/src/github.js#L947 Is happening in the npm version (v0.11.2)  ...

**Comment by clayreimann** [comment]
Looks like that functionality is as-yet unreleased.

**Comment by clayreimann** [comment]
@msdark v1.0.0 has been released, please re-open if this is not fixed.
