### ISSUE TITLE
Create New Gists?

### ISSUE THREAD

**Issue by enki-code** [michael/github#312]
The documentation only explains how to get Gists that have already been created, using the getGist method.

How can I create new Gists?

**Comment by clayreimann** [comment]
Thanks for the comment. With the new release we're doing a major overhaul of all the documentation.

**Comment by enki-code** [comment]
Thanks for the reply, but, that still doesn't answer how I would go about creating a new gist or if it is even possible. I'm a huge fan of the library, just needs a little love. :+1:

**Comment by clayreimann** [comment]
Lots of love, and you can create a new gist with:

```javascript
var gist = github.getGist();
gist.create({/* gist data */});
```
