### ISSUE TITLE
Is there any way for anonymous user get public repos list of some user?

### ISSUE THREAD

**Issue by SilentImp** [michael/github#32]
Is there any way for anonymous user get public repos list of some user?
Why do you need github user if you want only read content of public repository?

**Comment by aendrew** [comment]
Closing as a duplicate of #187 — if you can do it, it's not documented, and it's thus a documentation issue. If you can't in fact do it (I know, it's hysterical I'm the current maintainer and I don't know whether you can or not... :sweat_smile:), I'll make sure that is possible in 0.10.8.
