### ISSUE TITLE
Get user's private organizations

### ISSUE THREAD

**Issue by cmbirk** [michael/github#323]
Right now user.getOrgs() is hitting the route mentioned here: https://developer.github.com/v3/orgs/#list-user-organizations

but it would be useful to include something like user.getAllOrgs() that hits the route here: https://developer.github.com/v3/orgs/#list-your-organizations

I'm happy to create a pull request with this functionality if you will accept that method @michael .

**Comment by clayreimann** [comment]
@cmbrik PRs are always welcome

**Comment by clayreimann** [comment]
Actually @cmbirk, If you create a user without passing a user name you'll get the functionality you're looking for. If you look at [this section](https://github.com/michael/github/blob/master/lib/User.js#L33-L52) of `User` you can see that if you pass a username you get the public summary endpoints, but if you don't then we default to the authenticated user.

In summary:
```js
let me = gh.getUser();
me.getOrgs().then(({data: allOrgs}) => {
  // here you have all your orgs
});

let cmbirk = gh.getUser('cmbirk');
cmbirk.getOrgs().then(({data: orgs}) => {
  // here you have your public orgs
});
```

This is a good gotcha that we should document more prominently though.

**Comment by cmbirk** [comment]
Ah, that's perfect.  Thanks for the heads up!
