### ISSUE TITLE
Problem when creating a gist

### ISSUE THREAD

**Issue by RaedsLab** [michael/github#337]
Following the documentation, when I try to create a gist in the browser using the following code:

```javascript 
       var gh = new GitHub();
        var gist = gh.getGist(); // not a gist yet
        gist.create({
            public: true,
            description: 'TEST',
            files: {
                "file1.txt": {
                    contents: "Aren't gists great!"
                }
            }
        }).then(function (httpResponse) {
            // Promises!
            var gist = httpResponse.data;
            gist.read(function (err, gist, xhr) {
                // if no error occurred then err == null

                // gist == httpResponse.data

                // xhr == httpResponse
            });
        });
```

This returns an error  `POST https://api.github.com/gists 422 (Unprocessable Entity)`

Can you reproduce? Any idea why?

**Comment by clayreimann** [comment]
I can see two issues with the snippet you posted:

1. Unautenticated users cannot create gists
1. You redefine `gist` in your promise handler so `gist.read` won't work

Other than that you appear to be doing the same thing we do in [the tests](https://github.com/michael/github/blob/master/test/gist.spec.js) so it should work.

**Comment by clayreimann** [comment]
@RaedsLab Any more thoughts here?

**Comment by guumaster** [comment]
I'm also getting an error, but it seems a 404 error: 

Here the code: 
```js
var gh = new GitHub({ token: MY_TOKEN });

var gist = gh.getGist();

gist.create({
   public: true,
   description: 'My first gist',
   files: {
      "file1.txt": {
         contents: "Aren't gists great!"
      }
   }
})

```

The lib  is posting this: 
```
  method: 'POST',
  url: 'https://api.github.com/gists',

  headers: 
     authorization: 'token e77..........VALID_TOKEN......0c',
     'content-type': 'application/json'

  body: 
     description: 'the description for this gist',
     public: true,
     files: { 'file1.txt': { content: 'String file contents' } } },

  json: true 
```

And the response is: 
```

{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/gists/#create-a-gist"
}
```

**Comment by clayreimann** [comment]
@guumaster Are you sure your token has the `gist` permission? Our tests indicate that we can successfully create gists using code almost identical to yours.

**Comment by guumaster** [comment]
sure, I'm using it with raw ajax calls and it works.

**Comment by clayreimann** [comment]
@guumaster @RaedsLab This is probably due to a mistake in the example from the readme reported in #374. Can you try with

```
{
   public: true,
   description: 'My first gist',
   files: {
      "file1.txt": {
         content: "Aren't gists great!"
      }
   }
}
```

**Comment by AurelioDeRosa** [comment]
This issue has been fixed, so I'm closing it.
