### ISSUE TITLE
Readme seems only to apply to v1.3.0

### ISSUE THREAD

**Issue by retog** [michael/github#338]
The User.getNotification method is only avalaible when using

    <script src="//npmcdn.com/github-api@v1.3.0/dist/GitHub.bundle.min.js"></script>

and not with 

    <script src="//npmcdn.com/github-api@v2.0.0/dist/GitHub.bundle.min.js"></script>

**Comment by clayreimann** [comment]
Good catch. That was one of the breaking changed in the 2.x series.
