### ISSUE TITLE
More examples (in readme or elsewhere)

### ISSUE THREAD

**Issue by retog** [michael/github#341]
It would be nice to have an example that shows how a repo is created, and how a file is added to it and modified.

**Comment by KristerV** [comment]
is any of this even possible?

**Comment by clayreimann** [comment]
@KristerV @retog have either of you looked at the [API documentation](http://michael.github.io/github/docs/2.3.0/index.html)? Is that something the people are likely to do when they are evaluating a library, or is it just when you're trying to troubleshoot issues?

@KristerV You certainly can [create a repo](http://michael.github.io/github/docs/2.3.0/User.html#createRepo) and [add files](http://michael.github.io/github/docs/2.3.0/Repository.html#writeFile)

**Comment by retog** [comment]
I have to admit that I missed the link to the documentation, once I found it I could solve my problem. Still I kept the issue open as I thought it might be good to have an example in the readme.

**Comment by KristerV** [comment]
Wow. Honestly I made effort clicking through [the front page](https://github.com/michael/github), but all I found was the [not so detailed docs](http://michael.github.io/github/). Adding this link to the repo readme would help a lot.
