### ISSUE TITLE
Unknown plugin "transform-es2015-modules-umd"

### ISSUE THREAD

**Issue by knowbody** [michael/github#343]
Currently using the library in a RN app, I get this error:

![image](https://cloud.githubusercontent.com/assets/3802023/15751625/090b19c2-28eb-11e6-9b12-cddc3d5dd84f.png)

usually this is caused by not excluding babel config from npm.

The possible solution would be to move the babel config from `package.json` file to `.babelrc` in the root directory and create `.npmignore` file to exclude `.babelrc` from the npm.

**.babelrc**
```json
{
  "babel": {
    "presets": [
      "es2015"
    ],
    "plugins": [
      [
        "transform-es2015-modules-umd",
        {
          "globals": {
            "es6-promise": "Promise"
          }
        }
      ]
    ],
    "env": {
      "development": {
        "sourceMaps": "inline"
      }
    }
  }
}
```

**.npmignore**
```
.babelrc
```

**Comment by clayreimann** [comment]
For my clarity, the problem is being caused because the babel config that exists in our `package.json` is being picked up by the tools you are using. Our babel config attempts to load the `transform-es2015-modules-umd` which is a devDependency for us and which you don't depend on so babel throws up when trying to run?

**Comment by knowbody** [comment]
@clayreimann exactly that

**Comment by knowbody** [comment]
for now I just added them to the project but I also get an error "debug is not a function in Requestable.js (line: 13)" any idea why?

**Comment by knowbody** [comment]
as I'm using it on the react-native project I need to make requests via `fetch()`, I'm going to for the library and do the changed for my project to work. Once I feel comfortable with my solution I will ping you back so maybe we can merge both. Feel free to close the issue.

**Comment by clayreimann** [comment]
@knowbody Sounds good. Looking forward to your PR.

**Comment by ebrillhart** [comment]
was there ever a permanent solution reached on this issue? or a consistently good workaround, at the very least?

**Comment by ebrillhart** [comment]
I've been running into this same issue and haven't been able to figure out a good workaround. Was there ever any follow-up on this?
