### ISSUE TITLE
Close and comment vs. comment and close

### ISSUE THREAD

**Issue by IAP-Reloaded** [michael/github#346]
As of right now, the issues manager has a button named "Close and comment" for commenting and closing at the same time. However, you are actually commenting **then** closing the issue.

This should be "Comment and close" instead.

**Comment by clayreimann** [comment]
Are you asking for new functionality? We don't currently have a way to close and comment (or comment and close).

**Comment by IAP-Reloaded** [comment]
No, this is the button next to the comment button for respiratory contributors. I can see it while I'm typing my message. Here is an image of it:

![screenshot of buttons](https://cloud.githubusercontent.com/assets/8007809/15901284/b194659c-2d70-11e6-9813-4f9063f9ccf1.png)

**Comment by clayreimann** [comment]
I think you might be confused, this repository is a js library that uses the GitHub API to replicate some of the functionality found on the website. 

We're not in any way affiliated with GitHub Inc. and we have no control over the website/API/anything like that. It sounds like you want to [open a support ticket](https://github.com/contact) with GitHub directly.

**Comment by IAP-Reloaded** [comment]
ok.

**Comment by muditgupta68** [comment]
hello

**Comment by chetanyakan** [comment]
![image](https://user-images.githubusercontent.com/35728906/95235511-5356b100-0823-11eb-8290-311565b4a57e.png)
