### ISSUE TITLE
How to create a repository?

### ISSUE THREAD

**Issue by Darker** [michael/github#373]
I cannot figure it out... I read both sourcecode and the testing code for repositories but it's too obscure. How do I do it?

**Comment by clayreimann** [comment]
You can either create a repository as a [user](http://michael.github.io/github/docs/2.3.0/User.html#createRepo) or as an [organization](http://michael.github.io/github/docs/2.3.0/Organization.html#createRepo)

**Comment by AurelioDeRosa** [comment]
Closing as this was not an issue anyway.
