### ISSUE TITLE
Simple write test failing

### ISSUE THREAD

**Issue by aausch** [michael/github#62]
github = new Github({ username:'username', password:'password', auth:"basic"})

user = github.getUser();

repos = ''

user.repos(function(err,r) { repos = r; })

repo = repos[0]

repoforwrite = github.getRepo('username',repo.name)

repoforwrite.write('gh-pages','test','test','test', function(err){alert(err);});
> 500 Server Internal Error

repo.permissions
> Object {admin: true, pull: true, push: true}

repoforwrite.listBranches(function(err,branches) { console.log(branches);})
> undefined
> gh-pages,master

**Comment by aendrew** [comment]
This is from like 2 years ago. Closing as unreproducible.
