### ISSUE TITLE
Support Gitlab API

### ISSUE THREAD

**Issue by edrex** [michael/github#68]
This is a placeholder issue to create a version of Github.js which works with Gitlab's HTTP API. The motivation is to allow Prose.io to work with self-hosted repos using Gitlab.

Gitlab is an opensource/self-hostable alternative to Github. It has a very similar data model (users, orgs, forks, etc), and an [HTTP API](https://github.com/gitlabhq/gitlabhq/tree/master/doc/api) of similar expressivity. 

There is a public service at https://gitlab.com/ for testing. 

Any other interest in such a port?

**Comment by aendrew** [comment]
I'd really like to close this issue TBTH; the goal of this library is to be a light implementation of the GitHub API, and I'm sure there are much better libraries for interacting with GitLab than this.

If anyone is disappointed that I've done this, please make yourselves heard and I'll consider reopening. Many thanks!
