### ISSUE TITLE
repo.remove throws error

### ISSUE THREAD

**Issue by Pomax** [michael/github#84]
when using `repo.remove('gh-pages', 'file that exists', function(err) { console.error(err); });` I get the following error and callstack:

```
Uncaught TypeError: Cannot call method 'reject' of undefined -- github.js:532
(anonymous function) -- github.js:532
(anonymous function) -- github.js:347
```

I was trying to effect a "repo.replace" by first removing a file I know exists in the tree using `repo.remove` and then calling `repo.write` to put in a new copy with updated information, but the remove throws this error.

It appears that the `_` var in https://github.com/michael/github/blob/master/github.js#L532 does not actually point to anything.

**Comment by aendrew** [comment]
Thanks for the info here, but I'm concentrating work re: repo.remove on #108. Marking as duplicate, please continue discussion there. Thanks!
