### ISSUE TITLE
repo.update is missing

### ISSUE THREAD

**Issue by Pomax** [michael/github#85]
It seems that repo.update is currently missing, requiring a repo.remove `POST` followed by a repo.write `POST` instead of the single repo.update `PUT` operation. ref: http://developer.github.com/v3/repos/contents/#update-a-file

**Comment by aendrew** [comment]
@Pomax Sounds like you've got it. Prioritising this for next release.

**Comment by aendrew** [comment]
Bumping to 0.10.8, we really need to release 0.10.7.
